---
###############################################################################
# Example of an Ansible playbook that can be executed when a Nuage Enterprise #
# is created. The enterprise id is retrieved from the event itself.           #
#                                                                             #
# Will create a DomainTemplate with four ZoneTemplates and SubnetTemplates.   #
# Will also instantiate the domain.                                           #
###############################################################################

- hosts: localhost
  connection: local
  gather_facts: False
  roles:
  #
  # Extracts 'nuage_auth' and 'event' variables out of Automation Workspace.
  #
  - xlab_si.nuage_miq_automate

  tasks:
  #
  # Grab event data.
  #
  - name: Set the enterprise from the event information
    set_fact:
      enterprise_id: "{{ event.entity.ID }}"
  - debug: msg="Handling enterprise with ID - {{ enterprise_id }}"

  #
  # Do some work.
  #
  - name: Create DomainTemplate in Enterprise
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: DomainTemplate
      parent_type: Enterprise
      parent_id: "{{ enterprise_id }}"
      state: present
      match_filter: "name == 'DefaultTemplate'"
      properties:
        name: "DefaultTemplate"
        description: "Template created automatically by Cloudforms when Enterprise is created"
      children:
      - type: ZoneTemplate
        properties: 
          name: "AppZone"
        children:
        - type: SubnetTemplate
          match_filter: "name == 'AppNet'"
          properties:
            name: AppNet
            address: 10.10.10.0
            netmask: 255.255.255.0
      - type: ZoneTemplate
        properties: 
          name: "DBZone"
        children:
        - type: SubnetTemplate
          match_filter: "name == 'DBNet'"
          properties:
            name: DBNet
            address: 10.10.20.0
            netmask: 255.255.255.0
      - type: ZoneTemplate
        properties: 
          name: "FrontZone"
        children:
        - type: SubnetTemplate
          match_filter: "name == 'FrontNet'"
          properties:
            name: FrontNet
            address: 10.10.30.0
            netmask: 255.255.255.0
      - type: ZoneTemplate
        properties: 
          name: "LBZone"
        children:
        - type: SubnetTemplate
          match_filter: "name == 'LBNet'"
          properties:
            name: LBNet
            address: 10.10.99.0
            netmask: 255.255.255.0
      - type: IngressACLTemplate
        match_filter: "name == 'AllowAll'"
        properties: 
          name: AllowAll
          active: true
          allow_address_spoof: false
          default_allow_ip: true
          default_allow_non_ip: true
      - type: EgressACLTemplate
        match_filter: "name == 'AllowAll'"
        properties: 
          name: AllowAll
          active: true
          default_allow_ip: true
          default_allow_non_ip: true
          default_install_acl_implicit_rules: true
    register: nuage_domain_template

  - name: Create Domains from the template
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: Domain
      parent_type: Enterprise 
      parent_id: "{{ enterprise_id }}"
      state: present
      match_filter: "name == 'CloudformsAnsible'"
      properties:
        name: "CloudformsAnsible"
        template_id: "{{ nuage_domain_template.id }}"
