---
- name: Nuage event callback
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    manageiq_validate_certs: True
  pre_tasks:
  - debug: msg="Running printout with cert validation"
  roles:
  - role: xlab_si.nuage_miq_automate
    validate_certs: False
  tasks:
  - debug: msg="I am a playbook running as event callback and I am able to access nuage credentials"
  - debug: var=nuage_auth
  - debug: msg="As well as details of the event that triggered me"
  - debug: var=event
  - debug: msg="So I'm now ready to do some work (and the certs are valid)!"
